### ISSUE TITLE
AddInstance method misworking

### ISSUE THREAD

**Issue by grigoriy-anichtchenkov** [AutomationML/AMLEngine2.1#19]
A method  **AddInstance** of the extension seemed to have another idea when was created

As I understand the idea: add **IE** instance of a **SystemUnitClass** to another **IE** in the **InstanceHierarchy**

What it actually does: adds **IE** to a **SystemUnitClass** unit...

```
        public static bool AddInstance(this SystemUnitClassType systemUnitClass, CAEXObject newInstanceObject)
        {
            if (systemUnitClass.Elements(newInstanceObject.TagName).Any((XElement n) => n.CAEXNameOfElement() == newInstanceObject.Name))
            {
                return false;
            }

            ExternalInterfaceType externalInterfaceType = newInstanceObject as ExternalInterfaceType;
            if ((object)externalInterfaceType == null)
            {
                return systemUnitClass.Insert((InternalElementType)newInstanceObject, asFirst: false);
            }

            return systemUnitClass.Insert(externalInterfaceType, asFirst: false);
        }
```

**Comment by josefprinz** [comment]
Sorry, that the AddInstance extension method is misleading. The AddInstance method works the same way as the Insert method and is therefore obsolete. The behavior is correct.

![AddInstance](https://user-images.githubusercontent.com/6409855/210068843-dd0e9e70-96cd-4b65-909c-cadda64bcd15.png)
