### ISSUE TITLE
DocumentVersionsHeader() only returns the first header information

### ISSUE THREAD

**Issue by kk738** [AutomationML/AMLEngine2.1#21]
When using the function DocumentVersionsHeader() it only returns the first element because internally it uses myCAEXFile.AdditionalInformation.ElementAndValues.**FirstOrDefault**. 
I would expect it to return all elements here so I can get all document versions:

Example AML:
```XML
<CAEXFile SchemaVersion="3.0" FileName="Diagnosticable Reactor V4.aml" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://www.dke.de/CAEX" xsi:schemaLocation="http://www.dke.de/CAEX CAEX_ClassModel_V.3.0.xsd">
  <AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-1:Manifest" Version="1.1.0" />
  </AdditionalInformation>
  <AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-4:ServiceSet" Version="1.0.0" />
  </AdditionalInformation>
  <AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-2:HmiSet" Version="1.0.0" />
  </AdditionalInformation>
  <AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-4:TextSet" Version="1.0.0" />
  </AdditionalInformation>
  <AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-4:ProcessValueSet" Version="1.0.0" />
  </AdditionalInformation>
....
</CAEXFile>
```

```C#
var caexDocument = CAEXDocument.LoadFromBinary(Resources.Mtps.Mtps.OnlyMtpLibraries);
var file = caexDocument.CAEXFile;

XElement xElement = file.DocumentVersionsHeader();  //only the first element will be return because FirstOrDefault is used internally
```

**Comment by josefprinz** [comment]
The correct usage of *DocumentVersions* is to add one *AdditionalInformation* Element and add all documents as child elements: 

```xml
<AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-1:Manifest" Version="1.1.0" />
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-4:ServiceSet" Version="1.0.0" />
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-2:HmiSet" Version="1.0.0" />
…
 </AdditionalInformation>
```

Therefore the engine gives only one version header for the Versions Header. 

The [BPR Paper from Dec. 2016](https://www.automationml.org/wp-content/uploads/2021/06/BPR_006E_Naming_Documents_and_Versions_Dec2016.pdf) where this feature is defined does not explicitly define how multiple documents are added and if multiple version headers are allowed.

It says: 

> “For each related document a “Document” tag shall be added.” 

This is implemented as a list of document elements with one parent DocumentVersions header. It also says:

> “Therefore, an additional  information block tag with the attribute “DocumentVersions="Recommendations”” shall be added. So other document types can be added in the same way”.

This  could be interpreted as they are multiple Document Version headers possible with different attributes like "Recommendations","..." but it also says: 

> “The value of this attribute “DocumentVersions” shall be “Recommendations”. 

This does not allow other headers than "Recommendations". It should be discussed in the AutomationML TAC if a clarification is necessary. 

I have tested the method CreateDocumentVersionsHeader of the engine and this method does not prevent to add multiple version headers. This means that an adjustment of the engine will be necessary in any case.

**Comment by josefprinz** [comment]
I have checked the behavior of the AMLEditor and the AMLEngine regarding the structure of the DocumentVersionInformation and found that this object is handled differently by the engine and the editor. The structure created by you corresponds to the version of the editor, the structure presented by me as an example corresponds to the engine. I will unify the different behaviors in the next few days and get back to you.

**Comment by josefprinz** [comment]
Changes are published

**Comment by tickietackie** [comment]
Just to be sure, I wanted to ask if this is sorted out now. 
Do I understand it correctly, that the "right" format by the standard is:

```xml
<AdditionalInformation DocumentVersions="Recommendations">
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-1:Manifest" Version="1.1.0" />
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-4:ServiceSet" Version="1.0.0" />
    <Document DocumentIdentifier="VDI/VDE/NAMUR 2658-2:HmiSet" Version="1.0.0" />
…
 </AdditionalInformation>
 ```

and the AmlEngine will from now on only use this format, right?

How can this be the only correct format, when the standard is vaguely formulated.
And will there be a clarification in the standard?

**Comment by josefprinz** [comment]
The Engine can only support one way to model DocumentVersion Information. The actual release only supports the compact form now.
