### ISSUE TITLE
Getting Started is not up-to-date

### ISSUE THREAD

**Issue by BohnSeb** [AutomationML/AMLEngine2.1#6]
Hello dear AutomationML-Team,
I wanted to start using the AutomationML Engine in my C# Project.

I tried to just do a simple programm, following your guide with the first steps.
It seems, that your instructions on this github are not up-to-date, as the line: "var myIH = caexDocument.CAEXFile.New_InstanceHierarchy("myIH");" throws errors, because New_InstanceHierarchy is not a valid command.

**Comment by AutomationML** [comment]
updated
