### ISSUE TITLE
NuGet-Packages should contain only one version

### ISSUE THREAD

**Issue by goebeler** [AutomationML/AMLEngine2.1#7]
when using the Aml.Engine.1.4.1 package you run into problems when trying to build mixed .net framwork and .net standard projects (i.e. .net framework application referencing .net standard project)

If both projects reference the Aml.Engine NuGet package it causes a compiler error:

![grafik](https://user-images.githubusercontent.com/8701639/84409665-ff89e180-ac0d-11ea-85dd-82cec5bee2e6.png)

The reason seems to be that multiple different aml engine versions are contained in the same package:

aml.engine.dll:
net4.6:              Version 1.3.3.0
net4.7:              Version 1.4.1.0
netcoreapp2.2:  Version 1.1.0.0
netcoreapp3.1:  Version 1.1.0.0
netstandard2.0: Version 1.1.0.0

AML.Engine.Services.dll:
net4.6:              Version 1.3.3.0
net4.7:              Version 1.4.0.0
netcoreapp2.2:  Version 1.2.2.0
netcoreapp3.1:  Version 1.2.2.0
netstandard2.0: Version 1.0.0.0

I have not tested if they really differ in any way but the version number.

**Comment by AutomationML** [comment]
I have commited version 1.7.3. Please check if this is o.k.
